import type { Questionnaire } from './types';

export const businessPlanQuestionnaire: Questionnaire = {
  id: 'business_plan',
  title: 'Business Plan',
  description: 'Tell us about your business idea and we\'ll create your plan',
  steps: [
    {
      id: 'the_basics',
      title: 'The Basics',
      description: 'Just the essentials about your business.',
      icon: 'Lightbulb',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'business_name',
          type: 'text',
          label: 'What do you want to call your business?',
          placeholder: 'e.g., Acme, TechFlow, Jane\'s Bakery',
          required: true,
        },
        {
          id: 'business_idea',
          type: 'textarea',
          label: 'Describe your business idea in your own words.',
          description: 'Don\'t worry about being polished. Just explain what you want to do.',
          placeholder: 'e.g., I want to help busy parents find reliable babysitters in their neighborhood through an app...',
          required: true,
          validation: { minLength: 20, maxLength: 1000 },
        },
        {
          id: 'industry',
          type: 'select',
          label: 'What industry is this in?',
          required: true,
          options: [
            { value: 'tech_software', label: 'Tech / Software / Apps' },
            { value: 'ecommerce', label: 'E-commerce / Online Store' },
            { value: 'food_beverage', label: 'Food & Beverage' },
            { value: 'health_wellness', label: 'Health & Wellness' },
            { value: 'education', label: 'Education / Training' },
            { value: 'finance', label: 'Finance / Fintech' },
            { value: 'real_estate', label: 'Real Estate' },
            { value: 'professional_services', label: 'Professional Services (consulting, agency, etc.)' },
            { value: 'retail', label: 'Retail / Physical Store' },
            { value: 'manufacturing', label: 'Manufacturing / Physical Products' },
            { value: 'entertainment', label: 'Entertainment / Media' },
            { value: 'travel', label: 'Travel / Hospitality' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'industry_other',
          type: 'text',
          label: 'What industry?',
          required: true,
          conditionalDisplay: { questionId: 'industry', value: 'other' },
        },
      ],
    },
    {
      id: 'your_customer',
      title: 'Your Customer',
      description: 'Who are you trying to help?',
      icon: 'Users',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'target_customer',
          type: 'textarea',
          label: 'Describe who you want to serve.',
          description: 'Be as specific as you can. If you\'re not sure, that\'s okay - just describe who you THINK would use this.',
          placeholder: 'e.g., Working moms in cities who need last-minute childcare help...',
          required: true,
          validation: { maxLength: 500 },
        },
        {
          id: 'customer_problem',
          type: 'textarea',
          label: 'What problem are you solving for them?',
          description: 'What frustration or pain point does your customer have?',
          placeholder: 'e.g., They can\'t find trustworthy babysitters quickly when plans change...',
          required: true,
          validation: { maxLength: 500 },
        },
        {
          id: 'why_you',
          type: 'textarea',
          label: 'Why would they choose you over other options?',
          description: 'What makes your solution better or different? It\'s okay to say "I\'m not sure yet".',
          placeholder: 'e.g., All our sitters are background-checked and can be booked in 2 hours...',
          required: false,
          validation: { maxLength: 500 },
        },
      ],
    },
    {
      id: 'business_model',
      title: 'How You\'ll Make Money',
      description: 'Don\'t worry if you\'re not sure - we\'ll help figure this out.',
      icon: 'DollarSign',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'how_make_money',
          type: 'select',
          label: 'How do you plan to make money?',
          required: true,
          options: [
            { value: 'sell_product', label: 'Sell a product (physical or digital)' },
            { value: 'subscription', label: 'Charge a subscription / membership fee' },
            { value: 'service_fee', label: 'Charge for services / hourly or project rate' },
            { value: 'commission', label: 'Take a commission / percentage of transactions' },
            { value: 'advertising', label: 'Advertising / sponsorships' },
            { value: 'freemium', label: 'Free basic version, charge for premium' },
            { value: 'not_sure', label: 'I\'m not sure yet - help me figure this out' },
          ],
        },
        {
          id: 'price_idea',
          type: 'textarea',
          label: 'Do you have any pricing in mind?',
          description: 'If you have ideas about what to charge, share them. If not, just say "not sure" and we\'ll research this for you.',
          placeholder: 'e.g., Maybe $20/month? Or I\'m not sure what people would pay...',
          required: false,
          validation: { maxLength: 300 },
        },
        {
          id: 'existing_revenue',
          type: 'select',
          label: 'Are you making any money from this yet?',
          required: true,
          options: [
            { value: 'no_revenue', label: 'No, this is just an idea' },
            { value: 'some_sales', label: 'Yes, I\'ve made a few sales' },
            { value: 'consistent', label: 'Yes, I have consistent revenue coming in' },
            { value: 'profitable', label: 'Yes, and I\'m profitable' },
          ],
        },
      ],
    },
    {
      id: 'your_situation',
      title: 'Your Situation',
      description: 'Help us understand where you\'re starting from.',
      icon: 'User',
      estimatedMinutes: 2,
      questions: [
        {
          id: 'current_stage',
          type: 'select',
          label: 'Where are you at right now?',
          required: true,
          options: [
            { value: 'idea', label: 'Just an idea - haven\'t started building yet' },
            { value: 'building', label: 'Building it / working on a prototype' },
            { value: 'launched', label: 'Launched but still early' },
            { value: 'growing', label: 'Have customers and trying to grow' },
            { value: 'established', label: 'Established business looking to scale or pivot' },
          ],
        },
        {
          id: 'working_on_this',
          type: 'select',
          label: 'Is this a solo project or do you have a team?',
          required: true,
          options: [
            { value: 'solo', label: 'Just me' },
            { value: 'cofounder', label: 'Me and a co-founder/partner' },
            { value: 'small_team', label: 'Small team (2-5 people)' },
            { value: 'larger_team', label: 'Larger team (5+ people)' },
          ],
        },
        {
          id: 'time_commitment',
          type: 'select',
          label: 'How much time can you dedicate to this?',
          required: true,
          options: [
            { value: 'side_project', label: 'Side project (few hours a week)' },
            { value: 'part_time', label: 'Part-time (10-20 hours/week)' },
            { value: 'full_time', label: 'Full-time (this is my main focus)' },
          ],
        },
        {
          id: 'funding_situation',
          type: 'select',
          label: 'What\'s your funding situation?',
          required: true,
          options: [
            { value: 'bootstrapping', label: 'Bootstrapping / using my own money' },
            { value: 'looking_funding', label: 'Looking for funding / investors' },
            { value: 'have_funding', label: 'Have some funding already' },
            { value: 'not_needed', label: 'Don\'t need funding - keeping it small' },
          ],
        },
      ],
    },
    {
      id: 'your_goals',
      title: 'Your Goals',
      description: 'What does success look like for you?',
      icon: 'Target',
      estimatedMinutes: 2,
      questions: [
        {
          id: 'success_vision',
          type: 'select',
          label: 'What\'s your vision for this business?',
          required: true,
          options: [
            { value: 'side_income', label: 'Nice side income ($1K-$5K/month)' },
            { value: 'replace_job', label: 'Replace my job income' },
            { value: 'small_business', label: 'Build a solid small business' },
            { value: 'scale_big', label: 'Scale it big / build a large company' },
            { value: 'exit', label: 'Build to sell / get acquired' },
            { value: 'not_sure', label: 'Not sure yet - open to possibilities' },
          ],
        },
        {
          id: 'timeline',
          type: 'select',
          label: 'What\'s your timeline?',
          required: true,
          options: [
            { value: 'asap', label: 'Want to move fast - launch ASAP' },
            { value: 'few_months', label: 'A few months to do it right' },
            { value: 'no_rush', label: 'No rush - building on the side' },
          ],
        },
        {
          id: 'biggest_challenge',
          type: 'textarea',
          label: 'What\'s your biggest question or challenge right now?',
          description: 'What do you most need help figuring out?',
          placeholder: 'e.g., I don\'t know how to find my first customers, or I\'m not sure if people will pay for this...',
          required: false,
          validation: { maxLength: 500 },
        },
        {
          id: 'anything_else',
          type: 'textarea',
          label: 'Anything else we should know?',
          description: 'Any context, constraints, or details that would help us give you better advice?',
          placeholder: 'e.g., I have experience in marketing, I\'m based in Austin, I can only invest $5K to start...',
          required: false,
          validation: { maxLength: 500 },
        },
      ],
    },
  ],
};
