import type { Questionnaire } from './types';

export const businessPlanQuestionnaire: Questionnaire = {
  planType: 'business_plan',
  totalEstimatedMinutes: 25,
  steps: [
    {
      id: 'basics',
      title: 'The Basics',
      description: "Let's start with the foundation - what is your business all about?",
      icon: 'Lightbulb',
      estimatedMinutes: 5,
      questions: [
        {
          id: 'business_name',
          type: 'text',
          label: 'What is your business name?',
          description: "Don't have one yet? That's okay - just use a working name.",
          placeholder: 'e.g., Acme Solutions',
          required: true,
          validation: { minLength: 2, maxLength: 100 },
        },
        {
          id: 'one_liner',
          type: 'textarea',
          label: 'In one sentence, what does your business do?',
          description: "Imagine you're explaining to a friend at a coffee shop.",
          placeholder:
            'e.g., We help small business owners automate their bookkeeping so they can focus on growing their business.',
          required: true,
          validation: { minLength: 20, maxLength: 300 },
          aiContext: 'This becomes the core value proposition and elevator pitch',
        },
        {
          id: 'business_stage',
          type: 'select',
          label: 'Where are you in your journey?',
          required: true,
          options: [
            { value: 'idea', label: 'Just an idea', description: "Haven't started building yet" },
            { value: 'building', label: 'Building', description: 'Working on the product/service' },
            { value: 'pre_launch', label: 'Pre-launch', description: 'Ready but not live yet' },
            { value: 'launched', label: 'Launched', description: 'Live with some customers' },
            { value: 'growing', label: 'Growing', description: 'Have customers, looking to scale' },
          ],
        },
        {
          id: 'industry',
          type: 'select',
          label: 'What industry are you in?',
          required: true,
          options: [
            { value: 'saas', label: 'Software / SaaS' },
            { value: 'ecommerce', label: 'E-commerce / Retail' },
            { value: 'services', label: 'Professional Services' },
            { value: 'healthcare', label: 'Healthcare / Wellness' },
            { value: 'education', label: 'Education / Training' },
            { value: 'fintech', label: 'Finance / Fintech' },
            { value: 'food_beverage', label: 'Food & Beverage' },
            { value: 'real_estate', label: 'Real Estate' },
            { value: 'media', label: 'Media / Entertainment' },
            { value: 'manufacturing', label: 'Manufacturing / Hardware' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'industry_other',
          type: 'text',
          label: 'Please specify your industry',
          required: true,
          conditionalDisplay: { questionId: 'industry', value: 'other' },
        },
      ],
    },
    {
      id: 'problem_solution',
      title: 'Problem & Solution',
      description: 'What problem are you solving and how?',
      icon: 'Target',
      estimatedMinutes: 5,
      questions: [
        {
          id: 'problem',
          type: 'textarea',
          label: 'What problem are you solving?',
          description: 'Describe the pain point your customers experience. Be specific.',
          placeholder:
            "e.g., Small business owners spend 10+ hours per month on bookkeeping, which takes time away from actually running their business. Most can't afford a full-time accountant.",
          required: true,
          validation: { minLength: 50, maxLength: 1000 },
          aiContext: 'This defines the market need and urgency',
        },
        {
          id: 'solution',
          type: 'textarea',
          label: 'How does your product/service solve this problem?',
          description: 'What is your approach? What makes it work?',
          placeholder:
            'e.g., Our AI-powered software automatically categorizes transactions, generates reports, and prepares tax documents, reducing bookkeeping time to under 1 hour per month.',
          required: true,
          validation: { minLength: 50, maxLength: 1000 },
        },
        {
          id: 'unique_value',
          type: 'textarea',
          label: 'What makes your solution different or better than alternatives?',
          description: 'Think about competitors, substitutes, or the "do nothing" option.',
          placeholder:
            'e.g., Unlike traditional accounting software, we use AI to eliminate manual data entry. Unlike hiring a bookkeeper, we cost $29/month instead of $500+.',
          required: true,
          validation: { minLength: 30, maxLength: 500 },
          aiContext: 'This becomes the competitive positioning',
        },
      ],
    },
    {
      id: 'target_customer',
      title: 'Your Ideal Customer',
      description: 'Who exactly are you building this for?',
      icon: 'Users',
      estimatedMinutes: 5,
      questions: [
        {
          id: 'target_customer_description',
          type: 'textarea',
          label: 'Describe your ideal customer in detail',
          description: 'Be specific: demographics, role, company size, situation, etc.',
          placeholder:
            "e.g., Solo service providers (consultants, freelancers, coaches) making $50K-$250K annually. They're tech-savvy but not technical, typically 30-50 years old, and value their time highly.",
          required: true,
          validation: { minLength: 50, maxLength: 800 },
        },
        {
          id: 'customer_acquisition_current',
          type: 'select',
          label: 'How are you finding customers today (or plan to)?',
          required: true,
          options: [
            { value: 'word_of_mouth', label: 'Word of mouth / Referrals' },
            { value: 'social_media', label: 'Social media (organic)' },
            { value: 'content_seo', label: 'Content marketing / SEO' },
            { value: 'paid_ads', label: 'Paid advertising' },
            { value: 'cold_outreach', label: 'Cold outreach (email, calls)' },
            { value: 'partnerships', label: 'Partnerships / Affiliates' },
            { value: 'events', label: 'Events / Networking' },
            { value: 'not_sure', label: 'Not sure yet' },
          ],
        },
        {
          id: 'market_size_estimate',
          type: 'select',
          label: 'How big do you think your target market is?',
          description: "A rough estimate is fine - we'll help you refine this.",
          required: true,
          options: [
            { value: 'niche', label: 'Niche (thousands of potential customers)' },
            { value: 'small', label: 'Small (tens of thousands)' },
            { value: 'medium', label: 'Medium (hundreds of thousands)' },
            { value: 'large', label: 'Large (millions)' },
            { value: 'unknown', label: 'Not sure' },
          ],
        },
      ],
    },
    {
      id: 'business_model',
      title: "How You'll Make Money",
      description: "Let's figure out your business model and pricing.",
      icon: 'DollarSign',
      estimatedMinutes: 5,
      questions: [
        {
          id: 'revenue_model',
          type: 'select',
          label: "What's your primary revenue model?",
          required: true,
          options: [
            {
              value: 'subscription',
              label: 'Subscription / Recurring',
              description: 'Monthly or annual fees',
            },
            {
              value: 'one_time',
              label: 'One-time purchase',
              description: 'Single payment for product/service',
            },
            { value: 'project', label: 'Project-based', description: 'Fixed price per project' },
            { value: 'hourly', label: 'Hourly / Time-based', description: 'Billing by time spent' },
            {
              value: 'commission',
              label: 'Commission / Transaction fee',
              description: 'Percentage of transactions',
            },
            { value: 'freemium', label: 'Freemium', description: 'Free base, paid upgrades' },
            {
              value: 'advertising',
              label: 'Advertising',
              description: 'Free for users, paid by advertisers',
            },
            { value: 'hybrid', label: 'Multiple / Hybrid', description: 'Combination of models' },
          ],
        },
        {
          id: 'pricing',
          type: 'textarea',
          label: 'What is your pricing (or planned pricing)?',
          description: 'Include any tiers, plans, or pricing ranges.',
          placeholder: 'e.g., Basic: $29/month, Pro: $79/month, Enterprise: Custom pricing',
          required: true,
          validation: { maxLength: 500 },
        },
        {
          id: 'unit_economics',
          type: 'textarea',
          label: 'What does it cost you to deliver your product/service?',
          description:
            'Include things like: hosting, materials, labor per customer, etc. "Not sure yet" is okay.',
          placeholder:
            'e.g., Server costs ~$2/customer/month, customer support ~$5/customer/month',
          required: false,
          validation: { maxLength: 500 },
        },
      ],
    },
    {
      id: 'goals_resources',
      title: 'Goals & Resources',
      description: 'What are you trying to achieve and what do you have to work with?',
      icon: 'Rocket',
      estimatedMinutes: 5,
      questions: [
        {
          id: 'goals_12_months',
          type: 'textarea',
          label: 'What do you want to achieve in the next 12 months?',
          description: 'Be specific: revenue targets, customer numbers, product milestones, etc.',
          placeholder: 'e.g., Reach $10K MRR, acquire 500 paying customers, launch mobile app',
          required: true,
          validation: { minLength: 30, maxLength: 500 },
        },
        {
          id: 'funding_status',
          type: 'select',
          label: 'How are you funding this venture?',
          required: true,
          options: [
            { value: 'bootstrapped', label: 'Self-funded / Bootstrapped' },
            { value: 'friends_family', label: 'Friends & Family investment' },
            { value: 'angel', label: 'Angel investors' },
            { value: 'vc', label: 'Venture capital' },
            { value: 'grants', label: 'Grants / Competitions' },
            { value: 'seeking', label: 'Currently seeking funding' },
            { value: 'revenue', label: 'Revenue-funded (profitable)' },
          ],
        },
        {
          id: 'team_size',
          type: 'select',
          label: "What's your current team size?",
          required: true,
          options: [
            { value: 'solo', label: 'Just me' },
            { value: 'cofounders', label: '2-3 co-founders' },
            { value: 'small', label: 'Small team (4-10)' },
            { value: 'medium', label: 'Medium team (11-25)' },
            { value: 'large', label: 'Large team (25+)' },
          ],
        },
        {
          id: 'biggest_challenge',
          type: 'textarea',
          label: "What's your biggest challenge right now?",
          description: 'What keeps you up at night about this business?',
          placeholder:
            'e.g., Finding my first customers, building the product fast enough, running out of money',
          required: true,
          validation: { minLength: 20, maxLength: 500 },
        },
      ],
    },
  ],
};
