import type { Questionnaire } from './types';

export const businessPlanQuestionnaire: Questionnaire = {
  id: 'business_plan',
  title: 'Business Plan',
  description: 'Tell us about your business and we\'ll create your plan',
  steps: [
    {
      id: 'your_idea',
      title: 'Your Business Idea',
      description: 'Tell us what you want to build.',
      icon: 'Lightbulb',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'business_name',
          type: 'text',
          label: 'What\'s the name of your business?',
          description: 'Or what you want to call it.',
          placeholder: 'e.g., TaskFlow, Sweet Treats Bakery, ConsultCo',
          required: true,
        },
        {
          id: 'product_service',
          type: 'textarea',
          label: 'What product or service will you offer?',
          description: 'Describe what you\'re selling or providing. Be as specific as you can.',
          placeholder: 'e.g., A mobile app that helps people track their daily habits and sends reminders... OR A catering service for corporate events specializing in healthy meals...',
          required: true,
          validation: { minLength: 30, maxLength: 1000 },
        },
        {
          id: 'problem_solved',
          type: 'textarea',
          label: 'What problem does this solve?',
          description: 'What pain point or need are you addressing?',
          placeholder: 'e.g., People struggle to build consistent habits because they forget or lose motivation...',
          required: true,
          validation: { minLength: 20, maxLength: 500 },
        },
        {
          id: 'industry',
          type: 'select',
          label: 'What industry is this in?',
          required: true,
          options: [
            { value: 'tech_software', label: 'Tech / Software / Apps' },
            { value: 'ecommerce', label: 'E-commerce / Online Store' },
            { value: 'food_beverage', label: 'Food & Beverage' },
            { value: 'health_wellness', label: 'Health & Wellness' },
            { value: 'education', label: 'Education / Training' },
            { value: 'finance', label: 'Finance / Fintech' },
            { value: 'real_estate', label: 'Real Estate' },
            { value: 'professional_services', label: 'Professional Services' },
            { value: 'retail', label: 'Retail / Physical Store' },
            { value: 'manufacturing', label: 'Manufacturing / Products' },
            { value: 'entertainment', label: 'Entertainment / Media' },
            { value: 'travel', label: 'Travel / Hospitality' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          id: 'industry_other',
          type: 'text',
          label: 'Please specify your industry',
          required: true,
          conditionalDisplay: { questionId: 'industry', value: 'other' },
        },
      ],
    },
    {
      id: 'target_market',
      title: 'Your Target Market',
      description: 'Who will buy from you?',
      icon: 'Users',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'target_customer',
          type: 'textarea',
          label: 'Who is your ideal customer?',
          description: 'Describe the person or business you want to serve. Include things like age, location, job, interests, or company type.',
          placeholder: 'e.g., Busy professionals aged 25-45 who want to improve their health but struggle to find time... OR Small businesses with 10-50 employees that need HR software...',
          required: true,
          validation: { minLength: 20, maxLength: 500 },
        },
        {
          id: 'market_size_knowledge',
          type: 'select',
          label: 'Do you know how big your market is?',
          required: true,
          options: [
            { value: 'yes_researched', label: 'Yes, I\'ve done research' },
            { value: 'rough_idea', label: 'I have a rough idea' },
            { value: 'no_idea', label: 'No idea - please help me figure this out' },
          ],
        },
        {
          id: 'market_size_details',
          type: 'textarea',
          label: 'What do you know about your market size?',
          description: 'Share any numbers or estimates you have. If you\'re not sure, describe the general opportunity.',
          placeholder: 'e.g., There are about 50 million people in the US who want to build better habits... OR I think there are thousands of small businesses in my city that need this...',
          required: false,
          validation: { maxLength: 500 },
          conditionalDisplay: { questionId: 'market_size_knowledge', value: ['yes_researched', 'rough_idea'] },
        },
        {
          id: 'geographic_focus',
          type: 'select',
          label: 'Where will you operate?',
          required: true,
          options: [
            { value: 'local', label: 'Local (city/region)' },
            { value: 'national', label: 'National (one country)' },
            { value: 'international', label: 'International / Global' },
            { value: 'online_global', label: 'Online - anyone can access it' },
          ],
        },
        {
          id: 'geographic_details',
          type: 'text',
          label: 'Which location(s) specifically?',
          placeholder: 'e.g., Austin, Texas OR United States OR North America and Europe',
          required: false,
        },
      ],
    },
    {
      id: 'competition',
      title: 'Competition',
      description: 'Who else is doing something similar?',
      icon: 'Target',
      estimatedMinutes: 2,
      questions: [
        {
          id: 'know_competitors',
          type: 'select',
          label: 'Do you know who your competitors are?',
          required: true,
          options: [
            { value: 'yes_know', label: 'Yes, I know my main competitors' },
            { value: 'some_idea', label: 'I know a few but not sure who else' },
            { value: 'no_idea', label: 'Not really - help me identify them' },
          ],
        },
        {
          id: 'competitors_list',
          type: 'textarea',
          label: 'Who are your competitors?',
          description: 'List any competitors you know of and what they do.',
          placeholder: 'e.g., Habitica - gamified habit tracking, Streaks - simple iOS app, Notion - people use it for habit tracking too...',
          required: false,
          validation: { maxLength: 500 },
          conditionalDisplay: { questionId: 'know_competitors', value: ['yes_know', 'some_idea'] },
        },
        {
          id: 'why_different',
          type: 'textarea',
          label: 'What makes you different or better?',
          description: 'Why would someone choose you over alternatives? It\'s okay if you\'re still figuring this out.',
          placeholder: 'e.g., We focus specifically on health habits with personalized recommendations... OR I\'m not sure yet, I need help figuring out my angle...',
          required: true,
          validation: { maxLength: 500 },
        },
      ],
    },
    {
      id: 'business_model',
      title: 'Business Model',
      description: 'How will you make money?',
      icon: 'DollarSign',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'revenue_model',
          type: 'select',
          label: 'How will you make money?',
          required: true,
          options: [
            { value: 'sell_product', label: 'Sell products (physical or digital)' },
            { value: 'subscription', label: 'Subscription / recurring payments' },
            { value: 'service_fee', label: 'Charge for services' },
            { value: 'commission', label: 'Take a commission on transactions' },
            { value: 'freemium', label: 'Free basic, paid premium' },
            { value: 'advertising', label: 'Advertising revenue' },
            { value: 'licensing', label: 'Licensing / white-label' },
            { value: 'not_sure', label: 'Not sure - help me decide' },
          ],
        },
        {
          id: 'pricing_thoughts',
          type: 'textarea',
          label: 'What are your thoughts on pricing?',
          description: 'Share any pricing ideas you have, or what similar products/services charge. Say "not sure" if you need help.',
          placeholder: 'e.g., I\'m thinking $9.99/month, competitors charge $5-15... OR Not sure what people would pay for this...',
          required: true,
          validation: { maxLength: 300 },
        },
        {
          id: 'current_status',
          type: 'select',
          label: 'What\'s your current status?',
          required: true,
          options: [
            { value: 'idea', label: 'Just an idea' },
            { value: 'planning', label: 'Planning / researching' },
            { value: 'building', label: 'Building the product/service' },
            { value: 'launched', label: 'Launched, getting first customers' },
            { value: 'growing', label: 'Have customers, trying to grow' },
          ],
        },
        {
          id: 'existing_revenue',
          type: 'text',
          label: 'Any revenue yet? (optional)',
          description: 'If you\'re already making money, share approximate numbers.',
          placeholder: 'e.g., $500/month, $0, About $2000 last month',
          required: false,
        },
      ],
    },
    {
      id: 'goals_resources',
      title: 'Your Goals & Resources',
      description: 'What are you aiming for and what do you have to work with?',
      icon: 'Rocket',
      estimatedMinutes: 3,
      questions: [
        {
          id: 'success_vision',
          type: 'select',
          label: 'What does success look like for you?',
          required: true,
          options: [
            { value: 'side_income', label: 'Side income ($1K-$5K/month)' },
            { value: 'replace_salary', label: 'Replace my salary' },
            { value: 'small_business', label: 'Build a solid small business' },
            { value: 'scale_big', label: 'Build a large, scalable company' },
            { value: 'get_acquired', label: 'Build to sell / get acquired' },
            { value: 'not_sure', label: 'Not sure yet' },
          ],
        },
        {
          id: 'revenue_goal',
          type: 'text',
          label: 'What\'s your revenue goal for the first year?',
          description: 'A rough target is fine. Say "not sure" if you need help setting a goal.',
          placeholder: 'e.g., $50,000, $10K/month, Not sure',
          required: true,
        },
        {
          id: 'team_situation',
          type: 'select',
          label: 'Who\'s working on this?',
          required: true,
          options: [
            { value: 'solo', label: 'Just me' },
            { value: 'cofounder', label: 'Me + co-founder(s)' },
            { value: 'small_team', label: 'Small team (2-5)' },
            { value: 'larger_team', label: 'Larger team (5+)' },
          ],
        },
        {
          id: 'time_commitment',
          type: 'select',
          label: 'How much time can you dedicate?',
          required: true,
          options: [
            { value: 'few_hours', label: 'A few hours per week' },
            { value: 'part_time', label: 'Part-time (10-20 hrs/week)' },
            { value: 'full_time', label: 'Full-time' },
          ],
        },
        {
          id: 'funding_situation',
          type: 'select',
          label: 'What\'s your funding situation?',
          required: true,
          options: [
            { value: 'bootstrapping', label: 'Bootstrapping / self-funded' },
            { value: 'small_budget', label: 'Have a small budget to invest' },
            { value: 'seeking_funding', label: 'Looking for investors' },
            { value: 'have_funding', label: 'Already have funding' },
          ],
        },
        {
          id: 'startup_budget',
          type: 'text',
          label: 'How much can you invest to start? (optional)',
          placeholder: 'e.g., $1,000, $10,000, Nothing right now',
          required: false,
        },
        {
          id: 'biggest_challenge',
          type: 'textarea',
          label: 'What\'s your biggest challenge or question right now?',
          description: 'What do you most need help with?',
          placeholder: 'e.g., I don\'t know how to get my first customers, I\'m not sure if my pricing is right...',
          required: false,
          validation: { maxLength: 500 },
        },
      ],
    },
  ],
};
