import type { Questionnaire } from './types';

export const gtmPlanQuestionnaire: Questionnaire = {
  id: 'gtm_plan',
  title: 'Go-to-Market Plan',
  description: 'Create a comprehensive launch strategy for your product or service',
  steps: [
    {
      id: 'product_overview',
      title: 'What Are You Launching?',
      description: "Tell us about the product or service you're bringing to market.",
      icon: 'Package',
      estimatedMinutes: 4,
      questions: [
        {
          id: 'product_name',
          type: 'text',
          label: 'What is the name of your product/service?',
          required: true,
          placeholder: 'e.g., TaskFlow Pro',
        },
        {
          id: 'product_description',
          type: 'textarea',
          label: 'Describe your product/service in 2-3 sentences',
          placeholder: 'What is it? What does it do? Who is it for?',
          required: true,
          validation: { minLength: 50, maxLength: 500 },
        },
        {
          id: 'launch_type',
          type: 'select',
          label: 'What type of launch is this?',
          required: true,
          options: [
            { value: 'new_product', label: 'Brand new product', description: 'First time in market' },
            {
              value: 'new_market',
              label: 'Existing product, new market',
              description: 'Expanding to new segment/geography',
            },
            {
              value: 'new_feature',
              label: 'Major feature/version',
              description: 'Significant update to existing product',
            },
            {
              value: 'rebrand',
              label: 'Rebrand/Repositioning',
              description: 'Same product, new positioning',
            },
          ],
        },
        {
          id: 'readiness',
          type: 'select',
          label: 'How ready is the product for launch?',
          required: true,
          options: [
            { value: 'concept', label: 'Concept/Design phase' },
            { value: 'development', label: 'In development' },
            { value: 'beta', label: 'Beta/Testing' },
            { value: 'ready', label: 'Ready to launch' },
            { value: 'soft_launch', label: 'Already soft-launched' },
          ],
        },
      ],
    },
    {
      id: 'target_market',
      title: 'Target Market',
      description: 'Who exactly are you going after with this launch?',
      icon: 'Target',
      estimatedMinutes: 4,
      questions: [
        {
          id: 'primary_persona',
          type: 'textarea',
          label: 'Describe your primary target customer',
          description: 'Demographics, job title, company size, pain points, goals',
          placeholder:
            'e.g., Marketing managers at B2B SaaS companies (50-200 employees) who struggle with creating consistent content and measuring ROI.',
          required: true,
          validation: { minLength: 50, maxLength: 600 },
        },
        {
          id: 'buying_journey',
          type: 'select',
          label: 'How do your target customers typically buy?',
          required: true,
          options: [
            {
              value: 'self_serve',
              label: 'Self-serve',
              description: 'Research and buy independently',
            },
            {
              value: 'assisted',
              label: 'Assisted',
              description: 'Need some help but can decide alone',
            },
            {
              value: 'consultative',
              label: 'Consultative',
              description: 'Require demos and discussions',
            },
            {
              value: 'enterprise',
              label: 'Enterprise',
              description: 'Long sales cycles, multiple stakeholders',
            },
          ],
        },
        {
          id: 'awareness_level',
          type: 'select',
          label: 'How aware is your target market of the problem you solve?',
          required: true,
          options: [
            { value: 'unaware', label: 'Unaware', description: "Don't know they have the problem" },
            {
              value: 'problem_aware',
              label: 'Problem-aware',
              description: 'Know the problem, looking for solutions',
            },
            {
              value: 'solution_aware',
              label: 'Solution-aware',
              description: 'Know solutions exist, comparing options',
            },
            {
              value: 'product_aware',
              label: 'Product-aware',
              description: 'Know about your product specifically',
            },
          ],
        },
        {
          id: 'geographic_focus',
          type: 'multiselect',
          label: "What's your geographic focus for this launch?",
          required: true,
          options: [
            { value: 'local', label: 'Local (city/region)' },
            { value: 'national', label: 'National (single country)' },
            { value: 'north_america', label: 'North America' },
            { value: 'europe', label: 'Europe' },
            { value: 'global', label: 'Global' },
          ],
        },
      ],
    },
    {
      id: 'competitive_landscape',
      title: 'Competition',
      description: 'Understanding your competitive landscape.',
      icon: 'Swords',
      estimatedMinutes: 4,
      questions: [
        {
          id: 'main_competitors',
          type: 'textarea',
          label: 'Who are your 2-3 main competitors?',
          description: 'Include direct competitors and alternatives (even "doing nothing")',
          placeholder:
            'e.g., 1) CompetitorA - established leader, expensive\n2) CompetitorB - similar features, poor UX\n3) Spreadsheets/manual process - free but time-consuming',
          required: true,
          validation: { minLength: 50, maxLength: 600 },
        },
        {
          id: 'competitive_advantage',
          type: 'textarea',
          label: "What's your key advantage over these competitors?",
          description: 'What can you credibly claim that they cannot?',
          required: true,
          validation: { minLength: 30, maxLength: 400 },
        },
        {
          id: 'market_position',
          type: 'select',
          label: 'How do you want to be positioned in the market?',
          required: true,
          options: [
            {
              value: 'premium',
              label: 'Premium / Best-in-class',
              description: 'Higher price, superior quality',
            },
            {
              value: 'value',
              label: 'Best value',
              description: 'Good quality, competitive price',
            },
            {
              value: 'budget',
              label: 'Budget / Accessible',
              description: 'Lower price, essential features',
            },
            {
              value: 'niche',
              label: 'Niche specialist',
              description: 'Best for a specific use case',
            },
            {
              value: 'innovative',
              label: 'Innovative / Disruptive',
              description: 'Completely new approach',
            },
          ],
        },
      ],
    },
    {
      id: 'gtm_strategy',
      title: 'Strategy & Channels',
      description: 'How will you reach your customers?',
      icon: 'Megaphone',
      estimatedMinutes: 4,
      questions: [
        {
          id: 'primary_channels',
          type: 'multiselect',
          label: 'Which marketing channels do you plan to use? (Select top 3)',
          required: true,
          options: [
            { value: 'content_seo', label: 'Content marketing & SEO' },
            { value: 'social_organic', label: 'Social media (organic)' },
            { value: 'social_paid', label: 'Paid social ads' },
            { value: 'search_ads', label: 'Paid search (Google Ads)' },
            { value: 'email', label: 'Email marketing' },
            { value: 'influencer', label: 'Influencer / Creator partnerships' },
            { value: 'pr', label: 'PR & Media coverage' },
            { value: 'community', label: 'Community building' },
            { value: 'events', label: 'Events & Webinars' },
            { value: 'partnerships', label: 'Strategic partnerships' },
            { value: 'cold_outreach', label: 'Cold outreach (sales-led)' },
            { value: 'referral', label: 'Referral program' },
            { value: 'product_led', label: 'Product-led growth' },
          ],
        },
        {
          id: 'marketing_experience',
          type: 'select',
          label: "What's your marketing experience level?",
          description: 'This helps us calibrate the complexity of recommendations.',
          required: true,
          options: [
            { value: 'beginner', label: 'Beginner', description: 'New to marketing' },
            {
              value: 'intermediate',
              label: 'Intermediate',
              description: 'Some experience, still learning',
            },
            { value: 'advanced', label: 'Advanced', description: 'Experienced marketer' },
          ],
        },
        {
          id: 'existing_audience',
          type: 'textarea',
          label: 'Do you have any existing audience or customer base?',
          description: 'Email list, social followers, beta users, existing customers, etc.',
          placeholder: 'e.g., 2,500 email subscribers, 800 Twitter followers, 150 beta users',
          required: false,
        },
      ],
    },
    {
      id: 'timeline_budget',
      title: 'Timeline & Budget',
      description: 'What are your constraints and goals?',
      icon: 'Calendar',
      estimatedMinutes: 4,
      questions: [
        {
          id: 'launch_date',
          type: 'date',
          label: 'When do you want to launch (or when did you launch)?',
          required: true,
        },
        {
          id: 'budget_range',
          type: 'select',
          label: "What's your marketing budget for the first 3 months?",
          required: true,
          options: [
            { value: 'zero', label: '$0 (time only)', description: 'Sweat equity, no spend' },
            { value: 'low', label: '$1 - $500/month', description: 'Minimal budget' },
            { value: 'medium', label: '$500 - $2,000/month', description: 'Moderate budget' },
            { value: 'high', label: '$2,000 - $10,000/month', description: 'Significant budget' },
            { value: 'enterprise', label: '$10,000+/month', description: 'Large budget' },
          ],
        },
        {
          id: 'success_metrics',
          type: 'textarea',
          label: 'What does success look like in 90 days?',
          description: 'Be specific with numbers if possible.',
          placeholder: 'e.g., 100 paying customers, 1,000 signups, $5K MRR, 50 qualified leads',
          required: true,
          validation: { minLength: 20, maxLength: 300 },
        },
        {
          id: 'constraints',
          type: 'textarea',
          label: 'Any specific constraints or considerations?',
          description: 'Regulatory requirements, brand guidelines, team limitations, etc.',
          required: false,
        },
      ],
    },
  ],
};
